Repository honeycombio/otel-config-go, pull requests merged in 2023-05, with the labels that each got.

#36 fix: Don't fatal error when we can return an error
  otelconfig/otelconfig.go
  otelconfig/otelconfig_test.go
Labels: merge at will

#38 maint: cleanup go versions
  examples/Dockerfile
  go.mod
  go.sum
Labels: no-changelog, type: maintenance

#39 rel: prepare release 1.9.0
  CHANGELOG.md
  otelconfig/version.go
Labels: no-changelog

#40 maint(deps): bump go.opentelemetry.io/otel from 1.15.1 to 1.16.0
  go.mod
  go.sum
  otelconfig/pipelines/metrics.go
Labels: status: oncall
