Repository honeycombio/otel-config-go, pull requests merged in 2023-07, with the labels that each got.

#53 maint: update ubuntu and collector versions in CI
  .circleci/config.yml
  smoke-tests/docker-compose.yml
Labels: version: no bump, no-changelog, type: maintenance

#54 docs: Update WithExporterProtocol in README.md
  README.md
Labels: type: documentation, version: no bump, status: oncall

#48 feat: Add WithResourceOption for additional resource configuration
  examples/main.go
  otelconfig/otelconfig.go
  otelconfig/otelconfig_test.go
  smoke-tests/docker-compose.yml
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
Labels: type: enhancement, version: bump minor

#57 rel: prepare 1.11.0
  CHANGELOG.md
  otelconfig/version.go
Labels: no-changelog

#58 docs: fix typo in changelog
  CHANGELOG.md
Labels: type: documentation, no-changelog
