Repository honeycombio/otel-config-go, pull requests merged in 2023-08, with the labels that each got.

#59 feat: return errors from resource.New
  otelconfig/otelconfig.go
  otelconfig/otelconfig_test.go
Labels: type: enhancement, status: oncall

#60 maint: Match semantic convention version to SDK semantic conventions
  README.md
  RELEASING.md
  go.mod
  go.sum
  otelconfig/otelconfig.go
  otelconfig/otelconfig_test.go
Labels: type: bug, version: bump minor, type: maintenance

#61 rel: prep release v1.12.0
  CHANGELOG.md
  README.md
  otelconfig/version.go
Labels: no-changelog

#62 maint: add release.yml for auto-generated release notes
  .github/release.yml
Labels: no-changelog, type: maintenance
