Repository honeycombio/otel-config-go, pull requests merged in 2023-03, with the labels that each got.

#14 maint: Bump OTel dependenceis to latest
  go.mod
  go.sum
Labels: type: maintenance

#15 docs: Add explicit version to go get command in README
  README.md
  RELEASING.md
Labels: type: documentation

#17 fix: `launcher.WithSampler` doesn't get passed all the way through
  launcher/launcher.go
  launcher/launcher_test.go
Labels: type: bug, version: bump patch

#20 rel: prepare release v0.3.1
  CHANGELOG.md
  README.md
  launcher/version.go
Labels: no-changelog

#22 maint: add dependabot to project
  .github/dependabot.yml
Labels: version: no bump, no-changelog, type: maintenance
