Repository honeycombio/otel-config-go, pull requests merged in 2023-11, with the labels that each got.

#87 maint: update go-contrib packages to v1.21.0/v0.46.0
  go.mod
  go.sum
Labels: type: maintenance

#84 maint: Bump OTel dependencies
  .circleci/config.yml
  go.mod
  go.sum
Labels: breaking-change, version: bump minor, type: maintenance

#89 rel: Prepare v1.13.0 release
  CHANGELOG.md
  README.md
  otelconfig/version.go
Labels: no-changelog, type: maintenance

#91 maint: combine otel core and contrib in dependabot groups
  .github/dependabot.yml
  README.md
Labels: version: no bump, no-changelog, type: maintenance

#92 fix(pipelines): use protocol constants
  otelconfig/pipelines/metrics.go
  otelconfig/pipelines/trace.go
Labels: version: bump patch, type: maintenance, status: oncall
