Repository honeycombio/otel-config-go, pull requests merged in 2023-01, with the labels that each got.

#2 fix: fix file name
  launcher/launcher_test.go
Labels: type: maintenance

#3 maint: add circleci config
  .circleci/config.yml
  Makefile
Labels: version: no bump, type: maintenance

#1 fix: Omit config fields we cannot serialise
  launcher/launcher.go
  launcher/launcher_test.go
Labels: type: bug, version: bump patch

#5 rel: prep release v0.1.0
  CHANGELOG.md
  README.md
  RELEASING.md
  launcher/version.go
Labels: version: no bump, no-changelog
