Repository honeycombio/otel-config-go, pull requests merged in 2023-04, with the labels that each got.

#25 ci: add go 1.20 to ci
  .circleci/config.yml
Labels: no-changelog, type: maintenance

#26 feat: Allow vendors to set default exporter endpoint
  launcher/launcher.go
  launcher/launcher_test.go
Labels: type: enhancement, version: bump minor

#27 rel: Prepare v1.7.0 release
  CHANGELOG.md
  launcher/version.go
Labels: type: maintenance

#29 rel: v1.8.0 (rename to otel-config-go)
  CHANGELOG.md
  README.md
  otelconfig/version.go
Labels: version: no bump, no-changelog
