Repository honeycombio/otel-config-go, pull requests merged in 2024-03, with the labels that each got.

#106 fix: Prefer environment variables over code configuration
  .gitignore
  otelconfig/otelconfig.go
  otelconfig/otelconfig_test.go
  smoke-tests/smoke-sdk-grpc.bats
  smoke-tests/smoke-sdk-http.bats
Labels: type: enhancement, status: blocked, version: bump minor

#107 rel: Prepare v1.14.0 release
  CHANGELOG.md
  otelconfig/version.go
Labels: no-changelog, type: maintenance

#112 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: version: no bump, no-changelog, type: maintenance

#113 maint: Update ubuntu image in workflows to latest
  .circleci/config.yml
Labels: version: no bump, type: maintenance
